Implementing and correcting the base set of swap strategies, plus wrapping swap moves as part of steps
TuringLang/MCMCTempering.jl pull request #143
Opened 2023-02-17 12:39 UTC by HarrisonWilde

Contributions:

- Merged the swap move part of a step with the step itself:
  - Rather than having some steps returned by `AbstractMCMC.sample` that correspond only to the result of swapping temperatures between chains, we carry out the check for whether we `should_swap` and do the `swap` itself as part of the `AbstractMCMC.step` and _always_ progress the chains using the underlying exploratory samplers / kernels as well, this leads to a 1:1 correspondence between `nsamples` specified at sample time and the total number of steps taken by the samplers, which is desirable.
- Implementations of standard swap strategies:
  - Provide correct implementations of `SingleRandomSwap`, `RandomSwap`, `ReversibleSwap` and `NonReversibleSwap` in line with their definitions in the referenced literature. Reversible and Non-Reversible schemes are particularly important for reasonable baseline performance of a functional PT package, as they increase our robustness to untuned temperature ladders.
  - Renamed `StandardSwap` to `SingleSwap` for clarity.
  - Added `NoSwap` for debugging / disabling of swap functionality.
- Cleaned up `swapping.jl`:
  - Generalised to accept `i` and `j` inverse temperature indices to do a swap between.
  - Removed unnecessary `sampler.adapt` arg from `swap_attempt`
  - Clearer variable names and references

Pending TODO:

- Adaptation is sort of broken under this new approach, mainly due to us explicitly allowing swaps between non-neighbouring chains under the random permutation family of swap strategies. It should still be working for the non-random strategies though.
- Could further clean up `swapping.jl` by renaming the variables ending in `_other`, potentially remove the versions of functions that take many args given we are explicitly supporting `LogDensityProblems` as a base for most of we want to do for now, could add back more complex signatures for things like `compute_tempered_logdensities` if required down the line.

2023-02-17 12:54 UTC, torfjelde reviewed
Overall looks good! Left some comments though

2023-02-17 12:54 UTC, torfjelde commented on src/swapping.jl
> +function swap_attempt(rng, model, sampler, state, i, j)
I like this :+1:

2023-02-17 12:54 UTC, torfjelde commented on src/swapping.jl
> +    samplerᵢ = sampler_for_chain(sampler, state, i)
Unicode subscripts like this is generally not a good idea as depending on your language settings, etc. it might be rendered properly (unfortuantely).

2023-02-17 12:54 UTC, torfjelde commented on src/swapping.jl
> +    if sampler.adapt
I wouldn't do this. The sampler might only want to adapt the first few iterations or something, and we'd rather just have the caller of `swap_attempt` decide whether or not we should be adapting rather than having to mutate the sampler itself.

2023-02-17 12:54 UTC, torfjelde commented on src/swapping.jl
> +    NoSwap <: AbstractSwapStrategy
Hmm, I feel like we shouldn't need this; one could just create the different temperature models and run them in parallel, no?

2023-02-17 12:54 UTC, torfjelde commented on src/sampler.jl
> +    swap_every::Integer=10,
This I don't think is what you'd expect as a user :confused: I'd expect it to be 2 by default tbh.

But I've also been working on general compositions of samplers for AbstractMCMC, in which case all this should go away.

2023-02-17 12:56 UTC, torfjelde commented
> Merged the swap move part of a step with the step itself:

I'm confused; where is this happening? I'll have a closer look later; might have just missed it on the first viewing.

2023-02-17 12:58 UTC, HarrisonWilde commented on src/stepping.jl
> -    else
@torfjelde here is where the change to merge the swap move is happening

2023-02-17 13:00 UTC, HarrisonWilde commented on src/sampler.jl
> +    swap_every::Integer=10,
Given the changes to `AbstractMCMC.step`, the equivalent now would be defaulting this to 1. From a literature perspective, swapping every move is not really the expected behaviour. It is normal to do >1 steps of the exploratory kernels between each swap, 10 was an arbitrary choice but no worse than 1.

2023-02-17 13:01 UTC, HarrisonWilde commented on src/swapping.jl
> +    NoSwap <: AbstractSwapStrategy
True they could, potentially easier to just flip this switch though for specific debugging / manual tuning of a ladder?

2023-02-17 13:02 UTC, HarrisonWilde commented on src/swapping.jl
> +    if sampler.adapt
Ok, will revert this

2023-02-17 13:05 UTC, HarrisonWilde commented on src/swapping.jl
> +    if sampler.adapt
Actually though, for clarity, until we actually leverage this kind of thing, the argument for all of them is just going to be `sampler.adapt` anyway, is it not better to just keep stuff simple for now? When it comes to it we might think of a better way to be handling adaptation anyway (indeed I have some changes planned to the way the state and config is handled).

2023-02-21 10:26 UTC, torfjelde requested changes

2023-02-21 10:26 UTC, torfjelde commented on src/swapping.jl
> +    NoSwap <: AbstractSwapStrategy
Yeah I see the debugging and testing purpose, and on second thought it's probably worth it to keep it :+1:

2023-02-21 10:26 UTC, torfjelde commented on src/swapping.jl
> +    if sampler.adapt
But surely we're moving away from `sampler.adapt`, not away from passing `isadapt` as an argument? So it's a bit unclear to me why we'd make this explicit change when it's moving in the opposite direction of what we want.

But this is not a make-it-or-break issue; I'm just not quite on board regarding the reasoning :shrug:

2023-02-21 10:26 UTC, torfjelde commented on src/stepping.jl
> +Return a new `state`, with temperatures potentially swapped according to `strategy`.
```suggestion
Return a new `state`, with temperatures possibly swapped according to `strategy`.
```

2023-02-21 10:26 UTC, torfjelde commented on src/sampler.jl
> +    swap_every::Integer=10,
> Given the changes to AbstractMCMC.step, the equivalent now would be defaulting this to 1.

Yep;  I suggested 2 before I saw this. But as discussed below, I don't think it's a great way to do things. I'll make a PR for the `CompositionSampler` to MCMCTempering today, and then we can try to move it over to AbstractMCMC where IMO it should live.

> It is normal to do >1 steps of the exploratory kernels between each swap, 10 was an arbitrary choice but no worse than 1. If you prefer we can set it to 1 though, In most of my trialling I have been setting to 5 or 10 or so

Am aware! I'm fine with setting the default to 10 if you think that's more appropriate.

2023-02-21 10:58 UTC, HarrisonWilde commented on src/swapping.jl
> +    if sampler.adapt
Fair enough, I will revert

2023-02-21 10:59 UTC, HarrisonWilde commented on src/sampler.jl
> +    swap_every::Integer=10,
Very interesting, will keep as is for now but keen to see this PR! We can rethink then.

2023-02-21 10:59 UTC, HarrisonWilde commented on src/stepping.jl
> -    else
Yeah this looks great!

2023-02-22 16:53 UTC, torfjelde approved these changes
LGTM! Just need to make sure tests are passing. You all good locally? I'll set up Github actions with CI in a PR now.

2023-02-22 17:37 UTC, HarrisonWilde commented
> LGTM! Just need to make sure tests are passing. You all good locally? I'll set up Github actions with CI in a PR now.

All passing on my end other than the final MH one for the Turing model

2023-02-23 10:26 UTC, HarrisonWilde commented on test/runtests.jl
> +            adaptor = StanHMCAdaptor(MassMatrixAdaptor(metric), StepSizeAdaptor(0.8, integrator))
We do currently, but see my PR #147 which will resolve it

2023-02-23 10:38 UTC, merged