Supporting multiple samplers via sampler prototyping (v2)
TuringLang/MCMCTempering.jl pull request #150
Opened 2023-02-23 11:01 UTC by HarrisonWilde

My approach is as follows:
1. A user can use our package via `tempered` or `tempered_sample`
2. In either case, they may wish to instantiate a sampler / samplers ahead of time, in which case they can provide them, _or_ they can provide a template function that can be used to generate a sampler, this is useful for using `MCMCTempering` with packages like `AdvancedHMC` where it may be appropriate to take different step sizes for each tempered density
3. This is resolved via `init_internal` in either call, and depending on whether `shared_sampler` is specified, sampling will take place with the resulting / provided list of samplers or the provided single sampler

For AHMC, one might want to do:

```julia
model, D, n_samples, inverse_temperatures = ...

function create_HMCSampler(model, D)
    # Define a Hamiltonian system
    initial_θ = rand(D)
    metric = DiagEuclideanMetric(D)
    hamiltonian = Hamiltonian(metric, model)
    integrator = Leapfrog(find_good_stepsize(hamiltonian, initial_θ))
    proposal = NUTS{MultinomialTS, GeneralisedNoUTurn}(integrator)
    adaptor = StanHMCAdaptor(MassMatrixAdaptor(metric), StepSizeAdaptor(0.8, integrator))
    return AdvancedHMC.HMCSampler(proposal, metric, adaptor)
end

samples_tempered = tempered_sample(
   model,
   model -> create_HMCSampler(model, D),
   n_samples,
   inverse_temperatures
)

# or, just creating a `TemperedSampler`

tempered_sampler = tempered(
    model -> create_HMCSampler(model, D),
    inverse_temperatures;
    model=model
)

# or, sharing a pre-instantiated sampler

sampler_hmc = create_HMCSampler(model, D)
samples_tempered = tempered_sample(
    model,
    sampler_hmc,
    n_samples,
    inverse_temperatures;
    shared_sampler=true
)
```

TODO:

- Testing (not much to go wrong, but we should add some stuff to `runtests.jl` to verify this, I have some tests locally

2023-02-26 14:34 UTC, HarrisonWilde commented on test/runtests.jl
> +            compare_chains(chain_hmc, chain_tempered, atol=0.2, compare_std=false, compare_ess=false, isbroken=false)
It is hard to consistently beat non-tempered HMC here, presumably as both are performing near-optimally?

2023-02-27 19:49 UTC, torfjelde requested changes

2023-02-27 19:49 UTC, torfjelde commented on test/functions.jl
> +function test_and_sample_model(
Have you made changes to this function? If so, I'd recommend reverting the "moving" of these methods into a separate file, as it's quite difficult for a reviewer to identify where things have changed now :confused: 

And if not, i.e. this is _just_ moving the methods, I'd recommend calling the file `test_utils.jl` rather than `functions.jl`.

2023-02-27 19:49 UTC, torfjelde commented on test/functions.jl
> +        samples_tempered[findall((!).(getproperty.(states_tempered, :is_swap)))],
Does boolean indexing not work here? 

And if it really doesn't, then I'd recommend `findall(!Base.Fix2(getproperty, :is_swap), states_tempered))` instead.

2023-02-27 19:49 UTC, torfjelde commented on test/functions.jl
> +        typeof(sampler) <: Function ? sampler(model) : sampler,
This is not great. It also will fail if `sampler` is a callable struct that does not subtype `Function`.

2023-02-28 10:13 UTC, HarrisonWilde commented on test/functions.jl
> +        typeof(sampler) <: Function ? sampler(model) : sampler,
How about swapping to `typeof(sampler) <: AbstractMCMC.AbstractSampler ? sampler : sampler(model)` or do you have another suggestion? I did this as the old way of doing `sampler.sampler` doesn't work due to `bundle_samples` not expecting a `Vector`.

2023-02-28 10:14 UTC, HarrisonWilde commented on test/runtests.jl
> +            compare_chains(chain_hmc, chain_tempered, atol=0.2, compare_std=false, compare_ess=false, isbroken=false)
Yeah good idea, I will switch to that

2023-02-28 10:17 UTC, HarrisonWilde commented on test/functions.jl
> +function test_and_sample_model(
Good shout, I wanted to move them as it felt yeah they were more like testing utility functions than part of runtests itself, I can move them back to make the diff easier for now and then we could move them into `test_utils.jl` (better name I agree) just before merging?

2023-02-28 10:32 UTC, HarrisonWilde commented on test/functions.jl
> +        samples_tempered[findall((!).(getproperty.(states_tempered, :is_swap)))],
Will change to `samples_tempered[.!(getproperty.(states_tempered, :is_swap))]`, couldn't figure out a clean way to invert a bitarray when I wrote this!

2023-03-03 11:41 UTC, torfjelde commented on test/functions.jl
> +function test_and_sample_model(
I'd say just do the moving in a different PR. This way we keep track of changes better + refactoring PRs are quick and easy.

2023-03-03 11:44 UTC, torfjelde commented on test/functions.jl
> +        samples_tempered[findall((!).(getproperty.(states_tempered, :is_swap)))],
Why not `findall(!Base.Fix2(getproperty, :is_swap), states_tempered))`? This is nice because `!Base.Fix2(getproperty, :is_swap)` is static and is just a single function + broadcasting in this scenario seems unnecessarily complicated.

2023-03-03 11:47 UTC, torfjelde commented on test/runtests.jl
> +            progress=false, chain_type=MCMCChains.Chains
This depends on a particular version of AHMC, so I think we should add a compat bound for the testing.

2023-03-03 12:25 UTC, torfjelde requested changes
I'm still somewhat skeptical about our approach here.

- It increases the complexity of the `tempered` constructor. All the handling we have to do here is somewhat annoying.
- As of now, this is all about initialization of the samplers and is called once, i.e. it would trivial to make a `init_tempered` that the user can just call before `tempered`  to initialize the sampler.
- This doesn't quite seem like a long-term solution.
  - We also want to do adaption of the temperatures, and so if we first initialize a `sampler` using a particular temperature and then start changing said temperature, we'll probably also want to re-adapt the `sampler`. With the approach in this PR, how do we support reconstructing samplers further down the callstack?
  - It's often computationally intensive to set up the samplers, e.g. choosing the stepsize in `HMC` can be difficult, and so you'd prefer to just set up the `sampler` for the target posterior and then compute some deterministic parameters for the other samplers based on this first `sampler`. 

So all in all, I'm a bit uncertain because the current implementation satisfies a very particular need that can be replaced by one line of code prior to calling `tempered` + long-term we probably want to do something quite different to support more than just a `model -> sampler` mapping. 

IMO we just make a simple `init_internal_sampler` or something, which does the work and then `tempered_sampler` doesn't do any of this initialization. _But_ I'm also not going to fully stand in the way for this PR, so if you think it's still worth if after what the above reasoning I'm happy to merge it (once my current comments on the code has been addressed) :+1:

2023-03-03 12:25 UTC, torfjelde commented on src/sampler.jl
> +    return shared_sampler ? sampler : [deepcopy(sampler) for _ in eachindex(inverse_temperatures)]
This shouldn't really be needed. `AbstractSampler` shouldn't be mutated during the sampling process. I say we keep it for now, but maybe add a `# NOTE` something for the future to re-evaluate. For example, I can imagine scenarios where the sampler contains some large pre-computed matrix and this `deepcopy` will then be unfortunate.

```suggestion
    # TODO: Do we really need the `deepcopy` here? `sampler` shouidn't be mutated.
    return shared_sampler ? sampler : [deepcopy(sampler) for _ in eachindex(inverse_temperatures)]
```

2023-03-03 12:25 UTC, torfjelde commented on src/sampler.jl
> +    model=nothing,
I must say I'm not a huge fan of these `kwargs` that sometimes does something and sometimes does nothing depending on which type the first argument gets. From a user-perspective, if you want to try out different first-arguments here it becomes super-annoying since you also need to figure out which kwargs goes with the type.

A possibly less confusing approach is to wrap `sampler_template` in a type, e.g. do something like `LazySampler` which wraps a constructor and the `model`, etc. Then it's enough to just change the type of the first argument to get different behaviors.

2023-03-03 12:57 UTC, HarrisonWilde commented
> * It increases the complexity of the `tempered` constructor. All the handling we have to do here is somewhat annoying.
> * As of now, this is all about initialization of the samplers and is called once, i.e. it would trivial to make a `init_tempered` that the user can just call before `tempered`  to initialize the sampler.

I see what you mean here, but tbh I don't see the disadvantage in hiding this idea of an `init_tempered` function or similar from the user. It is likely to me for example that we definitely *don't* want a user to naively use tempering with a single AHMC sampler shared across all chains. I don't think we should remove this option (i.e. a user can specify explicitly that they want to do this using `shared_sampler`), but the default behaviour in most situations is likely to be either some function of a sampler or a list of samplers. I'm not against making an `init_internal_sampler` function callable by a user prior to calling `tempered`. However, given we have to provide this function either way, why not also call it as part of `tempered` should a user wish to just provide a standard sampler and get straight to sampling, sure it might be annoying for us but someone had to do it?

In my opinion, if we want this package to see general use, we will have to offer a fairly high touch approach to tempering on our part (as hopefully we will know more about it than the average user). I envision the package handling tempering in the same way NUTS is a sort of set and forget sampling schema. Ideally we design in a way to allow for easy customisation of the approach as well, but fundamentally we provide robust default behaviour for instantiating 10 AHMC samplers for 10 chains (rather than making a user do this manually which to me at least is a little clunky). For me the sweet spot is somewhere along the lines of this PR, although I expect it to change a bit when compositional sampler stuff is done.

> * This doesn't quite seem like a long-term solution.
>   
>   * We also want to do adaption of the temperatures, and so if we first initialize a `sampler` using a particular temperature and then start changing said temperature, we'll probably also want to re-adapt the `sampler`. With the approach in this PR, how do we support reconstructing samplers further down the callstack?

Afaict, as long as we pass the full `TemperedSampler` to `swap_attempt` we will have access to all of the samplers whenever we call `adapt!!`, as such we could easily wrap up re-adaptation of the samplers with adaptation of the ladder right? This seems more like a question of how to deal with having diff step sizes for AHMC etc. in general rather than an issue with this approach, unless I am misunderstanding.

>   * It's often computationally intensive to set up the samplers, e.g. choosing the stepsize in `HMC` can be difficult, and so you'd prefer to just set up the `sampler` for the target posterior and then compute some deterministic parameters for the other samplers based on this first `sampler`.

Good in theory but not sure how realistic this is, it would be an interesting contribution if we could show that under powered likelihoods the optimal step size can follow some fixed pattern, not sure if this is trivial or really complicated at first glance?

> 
> So all in all, I'm a bit uncertain because the current implementation satisfies a very particular need that can be replaced by one line of code prior to calling `tempered` + long-term we probably want to do something quite different to support more than just a `model -> sampler` mapping.

I think its worth having a conversation about this, but if we do want to support more than just model to sampler mappings then why not at least start from here rather than not supporting a function at all. Tbh the majority of my motivation for this proto sampler stuff comes from AHMC specifically. It looks like AHMC is being brought in line with AMCMC on some level through the introduction of `HMCSampler`, if there was also a generalised constructor provided for this too I think I could be tempted to drop the whole functional `proto_sampler` aspect of the PR. Somewhere, there needs to be the execution of ~five lines of code right now externally to AHMC to end up with a sampler object, ideally for me AHMC would instead have: `ahmc_sampler(initial_θ, metric, ...)` to replace a manual `create_HMCSampler`. IMO all AMCMC utilising packages should offer a function that gets you an `AbstractSampler`.

> 
> IMO we just make a simple `init_internal_sampler` or something, which does the work and then `tempered_sampler` doesn't do any of this initialization. _But_ I'm also not going to fully stand in the way for this PR, so if you think it's still worth if after what the above reasoning I'm happy to merge it (once my current comments on the code has been addressed) 👍

Pending the above, I could be convinced, but would probably want something similar to my big spiel at the top in the package on top of the compositional sampler PR's that are incoming for the reasons I outline there.

2023-03-03 12:59 UTC, HarrisonWilde commented on src/sampler.jl
> +    return shared_sampler ? sampler : [deepcopy(sampler) for _ in eachindex(inverse_temperatures)]
In your main message, you mention re-adapting the sampler, is this not the precise reason we want to deepcopy it, s.t. each sampler can be adapted separately?

2023-03-03 13:00 UTC, HarrisonWilde commented on src/sampler.jl
> +    model=nothing,
Agree this is not ideal, will have a think.

2023-03-03 13:01 UTC, HarrisonWilde commented on src/sampler.jl
> +        inverse_temperatures::Union{Integer, Vector{<:Real}};
Might be due to my experience in other languages, but if you don't support this then how do you suggest we ensure a valid `inverse_temperatures` is passed and fail gracefully? A check for the type in the function or something instead?

2023-03-03 13:03 UTC, HarrisonWilde commented on test/runtests.jl
> +        typeof(sampler) <: AbstractMCMC.AbstractSampler ? sampler : sampler(model),
yeah, as in your PR I think it could be better to just require the user to give the `tempered_sampler`, need to think more seriously about whether we want to support BOTH options or not, does it make sense to? To me `bundle_samples` is a little confusing conceptually, a lot of the time it does nothing, unless we pass Chains, so why is the sampler even required at all.. With a clearer answer to that we can make a call on whether to support both options or not.

2023-03-03 13:04 UTC, HarrisonWilde commented on src/sampling.jl
> +    proto_sampler::Union{<:Function,Vector{<:AbstractMCMC.AbstractSampler},AbstractMCMC.AbstractSampler},
No

2023-03-03 13:04 UTC, HarrisonWilde commented on test/runtests.jl
> +            progress=false, chain_type=MCMCChains.Chains
Fair enough yeah

2023-03-03 17:49 UTC, HarrisonWilde commented
There are some small refactoring changes to take away here, but I think it is best to close this PR for now, we can revisit the concepts after the big compositional sampler changes are done, as discussed.

2023-03-03 17:49 UTC, closed without merging