Introduction of compositions and products of samplers and models
TuringLang/MCMCTempering.jl pull request #151
Opened 2023-03-03 01:16 UTC by torfjelde

As we've spoken about before, it should be possible to make things much more composable than it currently is.

Much of this functionality is useful beyond just MCMCTempering, and so this package will provide a great "testing-ground" for functionality that we can eventually move to something like AbstractMCMC proper.

To achieve the above we need the following:
1. Compositions of samplers: `sampler_outer ∘ sampler_inner` whose `step` first steps `sampler_inner` and then, using the resulting state from stepping `sampler_inner`, takes a step with `sampler_outer`.
2. Products of samplers and models: `sampler_1 × sampler_2` which targets `model_1 × model_2` whose `step` simply runs `sampler_1` on `model_1` and `sampler_2` on `model_2` in "parallel".
3. A state (`SequentialState`) which represents a _sequence_ of states so we can later "unroll" these to obtain the full chain, if so desired. E.g. in the case of `sampler_outer ∘ sampler_inner` it's not completely obvious if we only want the iterations corresponding to the full composition, or if we actually want the iterations of each of the samplers.

All in all, it's now possible to do some neat thingies.

# Neat thingies

Some setup.

```julia
julia> using MCMCTempering

julia> using Distributions: Distributions

julia> using AdvancedMH, LogDensityProblems, MCMCChains

julia> using Random, LinearAlgebra

julia> Random.seed!(42);

julia> # Target of interest.
       struct Problem end

julia> LogDensityProblems.capabilities(::Type{Problem}) = LogDensityProblems.LogDensityOrder{0}()

julia> LogDensityProblems.dimension(::Problem) = 1

julia> function LogDensityProblems.logdensity(::Problem, x)
           Distributions.loglikelihood(
               Distributions.MixtureModel([
                   Distributions.Normal(0, 1),
                   Distributions.Normal(5, 1)
               ]),
               x
           )
       end

julia> model = Problem();

julia> # Make AdvancedMH.jl compatible with MCMCTempering.jl.
       MCMCTempering.getparams_and_logprob(transition::AdvancedMH.Transition) = transition.params, transition.lp
    
julia> function MCMCTempering.setparams_and_logprob!!(transition::AdvancedMH.Transition, params, logprob)
           return AdvancedMH.Transition(params, logprob)
       end

julia> sampler = RWMH(Distributions.MvNormal(zeros(1), I));
```

Compositions:

``` julia
julia> # Compose the two samplers to make a single one.
       sampler_composed = sampler ∘ sampler;

julia> # 1000 iterations of the composed sampler, i.e. 2 × 1000 iterations of `sampler`.
       sample(model, sampler_composed, 1000; chain_type=MCMCChains.Chains, param_names=["x"], progress=false)
Chains MCMC chain (2000×2×1 Array{Float64, 3}):

Iterations        = 1:1:2000
Number of chains  = 1
Samples per chain = 2000
parameters        = x
internals         = lp

Summary Statistics
  parameters      mean       std   naive_se      mcse       ess      rhat 
      Symbol   Float64   Float64    Float64   Float64   Float64   Float64 

           x    3.0078    2.6408     0.0590    0.3406   31.2179    1.0001

Quantiles
  parameters      2.5%     25.0%     50.0%     75.0%     97.5% 
      Symbol   Float64   Float64   Float64   Float64   Float64 

           x   -1.5962    0.4158    3.9498    5.2639    6.8919

julia> # If we don't want the "intermediate" iterations, i.e. we only want 1000 iterations,
       # we can create the composition as follows:
       sampler_composed = MCMCTempering.CompositionSampler(sampler, sampler, Val(false));

julia> # 1000 iterations of the composed sampler, i.e. 2 × 1000 iterations of `sampler`
       # but only the second step of every iteration is kept.
       sample(model, sampler_composed, 1000; chain_type=MCMCChains.Chains, param_names=["x"], progress=false)
Chains MCMC chain (1000×2×1 Array{Float64, 3}):

Iterations        = 1:1:1000
Number of chains  = 1
Samples per chain = 1000
parameters        = x
internals         = lp

Summary Statistics
  parameters      mean       std   naive_se      mcse       ess      rhat 
      Symbol   Float64   Float64    Float64   Float64   Float64   Float64 

           x    2.7230    2.6231     0.0830    0.3842   15.6804    1.0199

Quantiles
  parameters      2.5%     25.0%     50.0%     75.0%     97.5% 
      Symbol   Float64   Float64   Float64   Float64   Float64 

           x   -1.4815    0.2105    3.5516    5.0038    6.7092
```

Same with "repeated" samplers (useful to avoid insane compilation times):

``` julia
julia> sampler_repeated = sampler^2;

julia> # 1000 iterations of the composed sampler, i.e. 2 × 1000 iterations of `sampler`.
       sample(model, sampler_repeated, 1000; chain_type=MCMCChains.Chains, param_names=["x"], progress=false)
Chains MCMC chain (2000×2×1 Array{Float64, 3}):

Iterations        = 1:1:2000
Number of chains  = 1
Samples per chain = 2000
parameters        = x
internals         = lp

Summary Statistics
  parameters      mean       std   naive_se      mcse       ess      rhat 
      Symbol   Float64   Float64    Float64   Float64   Float64   Float64 

           x    2.5271    2.7248     0.0609    0.3574   27.1560    1.0430

Quantiles
  parameters      2.5%     25.0%     50.0%     75.0%     97.5% 
      Symbol   Float64   Float64   Float64   Float64   Float64 

           x   -1.8869   -0.0602    3.2003    5.0825    6.4611

julia> # If we don't want the "intermediate" iterations, i.e. we only want 1000 iterations,
       # we can create the composition as follows:
       sampler_repeated = MCMCTempering.RepeatedSampler(sampler, 2, Val(false));

julia> # 1000 iterations of the composed sampler, i.e. 2 × 1000 iterations of `sampler`
       # but only the second step of every iteration is kept.
       sample(model, sampler_repeated, 1000; chain_type=MCMCChains.Chains, param_names=["x"], progress=false)
Chains MCMC chain (1000×2×1 Array{Float64, 3}):

Iterations        = 1:1:1000
Number of chains  = 1
Samples per chain = 1000
parameters        = x
internals         = lp

Summary Statistics
  parameters      mean       std   naive_se      mcse       ess      rhat 
      Symbol   Float64   Float64    Float64   Float64   Float64   Float64 

           x    1.9781    2.4649     0.0779    0.3164   41.3850    1.0136

Quantiles
  parameters      2.5%     25.0%     50.0%     75.0%     97.5% 
      Symbol   Float64   Float64   Float64   Float64   Float64 

           x   -1.6115   -0.1330    1.2264    4.4097    6.2514
```

Products:

``` julia
julia> using AbstractMCMC

julia> # The `×` operator is only overloaded for `AbstractMCMC.AbstractModel`.
       model_product = AbstractMCMC.LogDensityModel(model) × AbstractMCMC.LogDensityModel(model);

julia> # NOTE: Doesn't have a default implementation for `MCMCChains` as it's not quite
       # clear what should be the default behavior. Maybe make multiple chains?
       sample(model_product, sampler_product, 10; progress=false)
10-element Vector{MCMCTempering.MultipleTransitions{Tuple{AdvancedMH.Transition{Vector{Float64}, Float64}, AdvancedMH.Transition{Vector{Float64}, Float64}}}}:
 MCMCTempering.MultipleTransitions{Tuple{AdvancedMH.Transition{Vector{Float64}, Float64}, AdvancedMH.Transition{Vector{Float64}, Float64}}}((AdvancedMH.Transition{Vector{Float64}, Float64}([-0.6498344983944278], -1.8232280067987499), AdvancedMH.Transition{Vector{Float64}, Float64}([0.07207544062668315], -1.6146778048128319)))
 MCMCTempering.MultipleTransitions{Tuple{AdvancedMH.Transition{Vector{Float64}, Float64}, AdvancedMH.Transition{Vector{Float64}, Float64}}}((AdvancedMH.Transition{Vector{Float64}, Float64}([0.6943350457163211], -1.8530163355237135), AdvancedMH.Transition{Vector{Float64}, Float64}([0.07207544062668315], -1.6146778048128319)))
 MCMCTempering.MultipleTransitions{Tuple{AdvancedMH.Transition{Vector{Float64}, Float64}, AdvancedMH.Transition{Vector{Float64}, Float64}}}((AdvancedMH.Transition{Vector{Float64}, Float64}([-0.4856077380136814], -1.7299928226472097), AdvancedMH.Transition{Vector{Fl [...]

2023-03-03 17:55 UTC, HarrisonWilde commented
Great stuff, small comment first of all wrt your write up above, could you add a bullet for repeated samplers (`sampler^2`) similar to the product and composed samplers. This would add a bit of clarity I think as its a lot of new terms.

2023-03-03 18:51 UTC, HarrisonWilde requested changes

2023-03-03 18:51 UTC, HarrisonWilde commented on src/MCMCTempering.jl
>      state::TemperedState,
```suggestion
    state,
```

I think we should drop the type signature on state, as it means a user needs to somehow access the states to call `bundle_samples` manually, this was in my other PR

2023-03-03 18:51 UTC, HarrisonWilde commented on src/MCMCTempering.jl
> +    state::CompositionState,
```suggestion
    state,
```

Same as above

2023-03-03 18:51 UTC, HarrisonWilde commented on src/MCMCTempering.jl
> +    state::SequentialStates,
```suggestion
    state,
```

Same as above

2023-03-03 18:51 UTC, HarrisonWilde commented on src/MCMCTempering.jl
> +    state::SequentialStates,
```suggestion
    state,
```

Same as above

2023-03-03 18:51 UTC, HarrisonWilde commented on src/abstractmcmc.jl
> +getparams(model, state) = first(getparams_and_logprob(model, state))
To clarify, have you built this as the default so that to support tempering someone only needs to implement one function: `getparams_and_logprob` rather than `getparams` and `getlogprob` separately?

2023-03-03 18:51 UTC, HarrisonWilde commented on src/sampler.jl
> +    swap_every::Integer=1,
Agree with a name change proposal, I was thinking it might be worth adopting the micro- and macro-step terms I find myself using sometimes. Just an idea but we could make the arg for `tempered_sample` `n_macro_steps` and then for `tempered` `n_micro_steps`, equally could be inner and outer to match the compositional sampler definition.

2023-03-03 18:51 UTC, HarrisonWilde commented on src/sampler.jl
> +    swap_every ≥ 1 || error("`swap_every` must take a positive integer value greater ≥1.")
```suggestion
    swap_every ≥ 1 || error("`swap_every` must take a positive integer value.")
```

2023-03-03 18:51 UTC, HarrisonWilde commented on src/sampler.jl
> +    sampler_inner = sampler^swap_every
Is it possible to make `^` broadcastable and commutative, that way afaict a `MultiSampler` would be supported, as we want each component of a `sampler` to be stepped `swap_every` times right? I think this is worth tackling in this PR as its quite fundamental, imo the default should really be:
```julia
MultiSampler((sampler^swap_every for _ in eachindex(inverse_temperatures))
```
Right?

2023-03-03 18:51 UTC, HarrisonWilde commented on src/samplers/repeated.jl
> +RepeatedSampler(sampler, num_repeat) = RepeatedSampler(sampler, num_repeat, Val(true))
Why do you wrap booleans with `Val`, I am curious as haven't really encountered it

2023-03-03 18:51 UTC, HarrisonWilde commented on src/sampler.jl
> +    sampler_inner = sampler^swap_every
I might be misunderstanding the stuff in the samplers folder, but it seems you've implemented it such that it reverses a `RepeatedSampler` of `MultiSampler`s into a `MultiSampler` of `RepeatedSampler`s right? As such perhaps this doesn't even require what I suggest above, as it seems like already if you do `sampler ^ swap_every` and `typeof(sampler) == MultiSampler` it will give the desired default behaviour I illustrate above according to the end of the `multi.jl` file?

2023-03-03 18:51 UTC, HarrisonWilde commented on src/state.jl
> +    return state.transitions_and_states[1].transitions[I...]
Looking over these functions, I definitely think we should separate transitions_and_states as its becoming a bit messy. I would name them `inner_states` and `inner_transitions`. In the future when we want to make this code distributable, I believe it might be necessary to actually have one sampler and one state per worker right, is there a way to do this now, i.e. have a shared state that can be partitioned into different parts of memory or workers?

2023-03-03 18:51 UTC, HarrisonWilde commented on src/stepping.jl
> +    if isswap
This will all be redundant once we have the `CompositionalSampler` of `SwapSampler` and `InnerSampler` right?

2023-03-03 18:51 UTC, HarrisonWilde commented on src/stepping.jl
> +    multisampler = MultiSampler(getsampler(sampler, i) for i in 1:numtemps(sampler))
I believe this should happen in `tempered` as I have pointed out, rather than making one at every step, should we not instead swap the entries of a single persistent `MultiSampler`, or use the reference mappings on them directly?

2023-03-03 18:51 UTC, HarrisonWilde commented on src/stepping.jl
> +    multisampler = MultiSampler(getsampler(sampler, i) for i in 1:numtemps(sampler))
This applies to the non-initial `step` below too

2023-03-03 18:52 UTC, HarrisonWilde commented
Just had a proper go through and tested it out a bit, all seems to work and all looks great, happy to merge pending the suggestions and comments above.

2023-03-09 15:00 UTC, torfjelde commented on Project.toml
> +MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
How about me make them optional dependencies? I.e. using extensions on Julia >1.8 and Requires.jl on older versions?

2023-03-09 15:05 UTC, torfjelde commented on src/MCMCTempering.jl
>      state::TemperedState,
But we _are_ using methods that expects this type, no? 
The reason behind being restrictive with types here are:
1. `bundle_samples` should really just be compatible with whatever the `step` can return for that particular combination of inputs, hence it makes sense to specialize on the same types as we do in `step`.
2. Not specializing on the `state` here can potentially lead to unnecessary method ambiguities since this is heavily overloaded method.

2023-03-09 15:07 UTC, torfjelde commented on src/abstractmcmc.jl
> +getparams(model, state) = first(getparams_and_logprob(model, state))
Tempering, compositions, etc. And yes, it's so that the _bare minimum_ to get things working is to implement `getparams_and_logprob`, and then if you want to make sure that every computational path is as fast as possible, you can implement `getparams`, etc. For example, in certain cases we might only need the parameters and so it might be unnecessary to also get the logprob.

2023-03-09 15:07 UTC, torfjelde commented on src/sampler.jl
> +    swap_every::Integer=1,
I think we've addressed this nicely in the other PR; agree?

2023-03-09 15:12 UTC, torfjelde commented on src/samplers/repeated.jl
> +RepeatedSampler(sampler, num_repeat) = RepeatedSampler(sampler, num_repeat, Val(true))
`Val` converts a value into a typed instance, which means that the `saveall` below can be compiled away:) You can read more about it here: https://docs.julialang.org/en/v1/manual/types/#%22Value-types%22

2023-03-09 15:12 UTC, torfjelde commented on src/state.jl
> +    return state.transitions_and_states[1].transitions[I...]
Agreed:) This has been dealt with in #151 :+1:

2023-03-09 15:13 UTC, torfjelde commented on src/stepping.jl
> +    if isswap
Yep!

2023-03-09 15:16 UTC, torfjelde commented on Project.toml
> +MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
Actually, I think we maybe should keep MCMCChains as a dep for now because it means that we can just always return a `Chains` object in `sample` which will generally be much nicer to work with for a user rather than these nested transition types you see if you don't use MCMCchains :confused: 

We can look at making it optional later :+1:

2023-03-10 10:24 UTC, HarrisonWilde commented on src/sampler.jl
> +    swap_every::Integer=1,
Hmm sort of, see my comment on that PR

2023-03-11 14:27 UTC, merged