Introduction of `SwapSampler` + make `TemperedSampler`  a fancy version of `CompositionSampler`
TuringLang/MCMCTempering.jl pull request #152
Opened 2023-03-06 13:09 UTC by torfjelde

This PR is quite a mouthful and I'm still not quite done with it (one of the tests are failing we need more tests), but the gist is as follows:
1. `TemperedSampler` now becomes a simple (on-the-fly) wrapper of a `MultiSampler` and `SwapSampler`.
2. Swapping is separated into a `SwapSampler` which acts on `MultiModel`. This means that we can now also apply swaps to basically an arbitrary collection of models; it no longer has any ties to the "tempering". This can be done by simply composing a `SwapSampler` with a `MultiSampler`, e.g. `(sampler × sampler) ∘ swapsampler` (and, of course, providing a model that is `MultiModel`).

I will add more description and tests soon.

2023-03-07 20:10 UTC, torfjelde commented
I have some more changes coming here in the morrow :+1:

2023-03-08 09:35 UTC, HarrisonWilde requested changes

2023-03-08 09:35 UTC, HarrisonWilde commented on src/sampler.jl
> +Base.@kwdef struct TemperedSampler{SplT,A,SwapT,Adapt} <: AbstractMCMC.AbstractSampler
This is cool, so essentially auto generates a constructor? What are the benefits of this over a standard struct considering we already have what is essentially a constructor in `tempered` (albeit with some extra steps), all the typing and so on is already assured there.

2023-03-08 09:35 UTC, HarrisonWilde commented on src/sampler.jl
> +    adaptation_states::Adapt=nothing
I don't think we should keep the adaptation state in the sampler long term, this was part of the big PR I did a while ago but didn't make it into the smaller couple of offshoots. In my opinion this should form part of the state, if we do this the sampler should remain largely "static" at least conceptually which feels more correct to me.

2023-03-08 09:35 UTC, HarrisonWilde commented on src/sampler.jl
>      # FIXME: Remove the hard-coded `2` for swap-every, and change `should_swap` acoordingly.
```suggestion

```

2023-03-08 09:35 UTC, HarrisonWilde commented on src/samplers/multi.jl
> +# NOTE: If we're not working with a `MultiModel`, we assume we just have to pass it on.
pass it on here meaning we pass the same model through each time? Why not have some naive init for a `MultiModel`?

2023-03-08 09:35 UTC, HarrisonWilde commented on src/state.jl
> +# TODO: Should this depend on `orderinge`?
I have thought about this quite a bit, happy to discuss. I think it would be good to establish the preferable default behaviour for all these situations, maybe this is a question that applies more generally than just tempering. I think it is nice to show at a higher level of the code the explicit reference to the mappings, as this gives a user clarity on the existence of the mapping and so on. So I am tempted to say the way we have it now where each chain is sort of kept together and the mapping allows us to access the correct thing is the correct one.

2023-03-08 09:35 UTC, HarrisonWilde commented on src/stepping.jl
> +                multistate = last(AbstractMCMC.step(rng, multimodel, multisampler, multistate; kwargs...))
Why do we no longer need to count burn-in steps here? May have missed something

2023-03-08 09:35 UTC, HarrisonWilde commented on src/swapsampler.jl
> +    # TODO: Handle adaptation.
So for now have we turned off the ability to adapt, iiuc?

2023-03-08 09:35 UTC, HarrisonWilde commented on test/runtests.jl
> +    num_iterations_tempered = num_iterations
maybe we can totally remove the explicit referencing to `num_iterations_tempered` now?

2023-03-08 09:35 UTC, HarrisonWilde commented on test/runtests.jl
> +            # At MOST 1% of swaps should be successful.
😅

2023-03-08 20:18 UTC, torfjelde commented on src/ladders.jl
>  function check_inverse_temperatures(Δ)
Good point; def agree we should check if it's empty :+1:

2023-03-08 20:20 UTC, torfjelde commented on src/sampler.jl
> +Base.@kwdef struct TemperedSampler{SplT,A,SwapT,Adapt} <: AbstractMCMC.AbstractSampler
I think we should still keep `tempered` as it also allows further customization. The usage of `@kwdef` just makes it easier when you actually want to interact with the raw constructor itself (which I often find myself wanting).

More importantly, `@kwdef` doesn't have any downsides so why not do it? :shrug:

2023-03-08 20:22 UTC, torfjelde commented on src/sampler.jl
> +    adaptation_states::Adapt=nothing
I only left it here because I didn't want to make a change that was completely irrelevant to what the PR is trying to achieve, but I most certainly agree with you.

IMO `adapt` should just be some `Adaptor` of sorts, which in turn holds the different adaption-options, and then we also have an `adapt_state` in the `TemperedState`, etc. Seems like we're on the same page here.

2023-03-08 20:52 UTC, torfjelde commented on src/stepping.jl
> +                multistate = last(AbstractMCMC.step(rng, multimodel, multisampler, multistate; kwargs...))
Ah, I think that's just a mistake. But regarding this: IMO we shouldn't do a burn-in here. `step` has the `discard_initial` argument which does almost the same; we could address this by simply adding a `AbstractMCMC.step_warmup` or something which just defaults to `AbstractMCMC.step` but can be overloaded. This should be an easy PR to make to AbstractMCMC, and should be quick merge.

2023-03-08 20:54 UTC, torfjelde commented on src/swapsampler.jl
> +    # TODO: Handle adaptation.
Yep. IMO this shouldn't be in `swap_attempt`. Instead `swap_attempt` should return the information needed to adapt; if we're missing something, then we should add that to `state` which we can then extract later on to perform adaptation. 

We can't put the adaptation here anymore because `SwapSampler` has no notion of temperatures, etc.

2023-03-08 20:54 UTC, torfjelde commented on test/runtests.jl
> +            # At MOST 1% of swaps should be successful.
Sometimes you just gotta activate that caps-lock :shrug:

2023-03-08 20:54 UTC, torfjelde commented on test/runtests.jl
> +    num_iterations_tempered = num_iterations
Yeah, we can :+1:

2023-03-08 21:30 UTC, torfjelde commented on src/adaptation.jl
> +defaultscale(::Geometric, Δ) = float(eltype(Δ))(0.9)
> Or do we want to maintain support for Float16, Float32 etc. distinction?

Yep. Or more specifically, we want to respect the user's input-type, though in the case where the user provides something liike `[1]`, i.e. `Int[]`, we need to convert using `float`.

2023-03-09 11:06 UTC, torfjelde commented on src/MCMCTempering.jl
> +        state_for_chain(state.swapstate),
So `TemperedState` also implements `chain_to_process` and `process_to_chain`, so I just relaxed the type-constraints on `state_for_process` so now it also works with `TemperedState`.

2023-03-09 14:55 UTC, torfjelde commented on src/samplers/multi.jl
> +# NOTE: If we're not working with a `MultiModel`, we assume we just have to pass it on.
I removed this implementation. IMO it shouldn't be here, in particular when it's not properly tested and thought through. In the moment I thought it might make sense in some cases, but it seems dangerous to leave it here without further thought and testing.

Good catch; cheers!

2023-03-09 20:17 UTC, HarrisonWilde commented on src/stepping.jl
> +                multistate = last(AbstractMCMC.step(rng, multimodel, multisampler, multistate; kwargs...))
I like this alternative yeah, I was trying to solve it without having to work on AMCMC but agree 100% that would be the preferable setup. It would be interesting to allow for the initial steps to be carried out with one arbitrary sampler and then the main sampling with another.. I could see other use cases for this

2023-03-09 20:17 UTC, HarrisonWilde commented on src/swapsampler.jl
> +    # TODO: Handle adaptation.
Agreed

2023-03-09 20:31 UTC, HarrisonWilde requested changes
Alright, this is looking great. A couple of minor outstanding things and a couple of q's I had looking over it all again. Once those are sorted I am happy to go ahead and merge this.

2023-03-09 20:31 UTC, HarrisonWilde commented on src/MCMCTempering.jl
> +        state_for_chain(state, 1),
Nice

2023-03-09 20:31 UTC, HarrisonWilde commented on src/sampler.jl
> +    steps_per_swap::Integer=1,
Somewhere I made a comment about micro and macro steps. I still sort of prefer this, or outer and inner steps, because then it matches with the syntax and naming of `CompositionalSampler`. I know I am overanalysing but to me `steps_per_swap` implies somehow that we do `n` steps as part of the swap itself (which makes no sense). Are you opposed to outer / inner?

2023-03-09 20:31 UTC, HarrisonWilde commented on src/sampler.jl
> +    steps_per_swap ≥ 1 || error("`swap_every` must take a positive integer value greater ≥1.")
Is it not clearer here to say 
```suggestion
    steps_per_swap > 0 || error("`steps_per_swap` must take a positive integer value.")
```

2023-03-09 20:31 UTC, HarrisonWilde commented on src/swapsampler.jl
> +    # 1. Swap the models and leave ordering of (sampler, state)-pair unchanged.
On this, I had a thought, probably nothing. Is it a safe assumption we are making that model objects are always super lightweight under AMCMC, I know LogDensityProblems ones are, but is that true for other feasible model implementations?

2023-03-09 20:31 UTC, HarrisonWilde commented on src/swapsampler.jl
> +    @set! model.models = models_by_processes(ChainOrder(), chain2models, swapstate_prev)
This whole function is super nice now!

2023-03-09 20:31 UTC, HarrisonWilde commented on src/swapsampler.jl
> +        rng, model, outersampler, state_from(model, outerstate_prev, swapstate);
Agree with your comments above, have you tested this?

2023-03-09 20:31 UTC, HarrisonWilde commented on src/swapsampler.jl
> +    # TODO: Should we re-order the transitions?
IMO we should, having reflected on this a bit. I think ideally we do as little as possible in `bundle_samples`, I think guiding the hand of the user quite strongly on returning correctly assembled chains is in the interest of this package.

2023-03-09 20:31 UTC, HarrisonWilde commented on src/swapsampler.jl
> +    logπjθj, logπjθi = compute_logdensities(model_j, model_i, state_j, state_i)
Looking at this, maybe we should change these functions a bit such that given the four args they return all four logdensities, imo its a bit messy to have to run the function _we_ have designed in abstract twice in a row. Not a priority rn but think it could be something to change down the line.

2023-03-09 20:31 UTC, HarrisonWilde commented on src/utils.jl
> +function roundtrips(transitions::AbstractVector{<:TemperedTransition})
This is super nice!

2023-03-10 07:48 UTC, torfjelde commented on src/stepping.jl
> +                multistate = last(AbstractMCMC.step(rng, multimodel, multisampler, multistate; kwargs...))
Related: https://github.com/TuringLang/AbstractMCMC.jl/pull/117

2023-03-10 08:00 UTC, torfjelde commented on src/swapsampler.jl
> +    # 1. Swap the models and leave ordering of (sampler, state)-pair unchanged.
> Is it a safe assumption we are making that model objects are always super lightweight under AMCMC, I know LogDensityProblems ones are, but is that true for other feasible model implementations?

A model can be anything, so I wouldn't assume so now. But does this matter? We're not re-instantiating models or anything of the sort, right? We're just moving them around.

Of course in the case where we're working with multiple workers and doing tempering, we don't want to serialize the entire model, but instead just transfer the temperatures. But this will be best implemented as a `DistributedTemperedSampler` or something, as I think trying to make something that does both distributed and non-distributed will inevitably be inefficient on both.

2023-03-10 08:37 UTC, torfjelde commented on src/swapsampler.jl
> +    # TODO: Should we re-order the transitions?
Haha, so this is unfortuante because I sort of arrived at the opposite conclusion after pondering the problem :sweat_smile:

Re-ordering the `outertransition` has the conseuqences that:
1. :-1: The transition will no longer be in sync with the states.
2. :-1: `SwapTransition` doesn't really make much sense anymore, e.g. what does `chain_to_process` mean if `chain_to_process[1] = 2` but we already re-ordered the transitions?

_If_ we're going to do something like this, i.e. re-order everything to make sense for the end-user, I instead think we should just overload `bundle_samples` for `TemperedTransitions` which then re-orders everything and simply drops the `SwapTransition` part from all the transitions. This means that a user of `sample` will never see the un-ordered samples nor the `SwapTransition`. This I think I can get behind.

How does this sound?

Alternatively, we could make `SwapTransition` a more complex structure which behaves similarly to a `CompositionTransition` but _wraps_ the `outertransitione`. I'm slightly less keen on this idea as it will further complicate things + it won't work if we also want to allow compositions where the `SwapSampler` is the outer sampler rather than inner (in this case we'd need to re-order the samples from the _next_ transition, not the current one).

The latter point is also one of my main reasons why I think all of this should occur in the `bundle_samples` rather than in `step`: swaps might have implications for the _previous_ transition, e.g. if we do `swapsampler ∘ sampler` with `sampler` returning a `SequenceTransitions`, e.g. `RepeatedSampler`, then a successful swap in iteration `k` means that we need to re-order the transitions obtained in the _next_ (the `k + 1`-th) iteration, not the current (`k`-th).

We currently don't support this just because I didn't want to mess with that logic atm, but I have working implementations of `step` for this sort of thing, so I think it's def something we want to support in the future. 

In more generality, we would ideally allow swaps "anywhwere", i.e. `sampler1 ∘ swapsampler ∘ sampler2`, in which case it becomes very complicated unless we defer the re-ordering to the `bundle_samples`.

2023-03-10 08:40 UTC, torfjelde commented on src/swapsampler.jl
> +    logπjθj, logπjθi = compute_logdensities(model_j, model_i, state_j, state_i)
Yeah we could do that. Should we just do something like

```julia
function compute_logdensities_for_swap(model_i, model_j, state_i, state_j)
    logπiθi, logπiθj = compute_logdensities(model_i, model_j, state_i, state_j)
    logπjθj, logπjθi = compute_logdensities(model_j, model_i, state_j, state_i)

    return logπiθi, logπiθj, logπjθj, logπjθi
end
```

for now?

Could even make the entire block above into:

```julia
function compute_logdensities_for_swap(model::MultiModel, state::SwapState)
    # Extract the relevant transitions.
    state_i = state_for_chain(state, i)
    state_j = state_for_chain(state, j)
    # Evaluate logdensity for both parameters for each tempered density.
    # NOTE: `SwapSampler` should only be working with models ordered according to `ProcessOrder`,
    # never `ChainOrder`, hence why we have the below.
    model_i = model_for_chain(ProcessOrder(), sampler, model, state, i)
    model_j = model_for_chain(ProcessOrder(), sampler, model, state, j)

    return compute_logdensities_for_swap(model_i, model_j, state_i, state_j)
end
```

to make `swap_attempt` a bit less of a mouthful.

2023-03-10 10:06 UTC, HarrisonWilde commented on src/swapsampler.jl
> +    # 1. Swap the models and leave ordering of (sampler, state)-pair unchanged.
Yeah ok, a separate `DistributedTemperedSampler` resolves my worry here, all good.

2023-03-10 10:26 UTC, HarrisonWilde commented on src/swapsampler.jl
> +    # TODO: Should we re-order the transitions?
Yeah I see what you mean with the more complex alternative and agree it is not worth it. I am happy to follow an approach similar to the one you outline here

> If we're going to do something like this, i.e. re-order everything to make sense for the end-user, I instead think we should just overload bundle_samples for TemperedTransitions which then re-orders everything and simply drops the SwapTransition part from all the transitions. This means that a user of sample will never see the un-ordered samples nor the SwapTransition. This I think I can get behind.

I do see your logic with wanting all of it to happen in `bundle_samples` and am happy to go with what we have for now and can maybe do the above down the line.

2023-03-10 10:27 UTC, HarrisonWilde commented on src/swapsampler.jl
> +    logπjθj, logπjθi = compute_logdensities(model_j, model_i, state_j, state_i)
Yes, I agree with this, I would go the full way with both suggestions.

2023-03-10 12:19 UTC, torfjelde commented on src/sampler.jl
> +    steps_per_swap::Integer=1,
Well, so this is a method which constructs a _tempered_ sampler where we're doing "a swap step, and then some steps with sampler".

If you're a "regular" user, who probably doesn't think about how this might be implemented as a composition of a swapping sampler and a regular sampler, I think `steps_per_swap` is immediately understood as "number of steps with sampler for every swap we propose" which is exactly what it means.

Yes, once you're aware that it's actually just the inner sampler of a composition, etc. it might make less sense, _but_ this is generally not how this is viewed in the literature nor by regular users, right?

2023-03-10 12:21 UTC, HarrisonWilde commented on src/sampler.jl
> +    steps_per_swap::Integer=1,
Yeah ok sure, let's go with this!

2023-03-10 12:22 UTC, torfjelde commented on src/swapsampler.jl
> +        rng, model, outersampler, state_from(model, outerstate_prev, swapstate);
I haven't tested no, but it will work just fine.

_But_ I'm thinking that I'll remove this for now + remove implementation of `getparams_and_logprob` for `SwapState` because I don't think it's quite clear what it should be doing. Basically, should `getparams_and_logprob` return
1. ordered according to internal representation (i.e. processes), or
2. ordered according to the models (which most othe samplers will expect)?

Before we concluded the above I think it's best to just error.

2023-03-10 12:26 UTC, HarrisonWilde commented
Yep, I agree with this, it isn’t really clear to me either so maybe best to error for now, we need to think about this more.

On 10 Mar 2023, at 12:22, Tor Erlend Fjelde ***@***.***> wrote:



@torfjelde commented on this pull request.

________________________________

In src/swapsampler.jl<https://github.com/TuringLang/MCMCTempering.jl/pull/152#discussion_r1132303494>:

> +
+    # Step for the swap-sampler.
+    swaptransition, swapstate = AbstractMCMC.step(
+        rng, model, swapsampler, state_from(model, swapstate_prev, outerstate_prev);
+        kwargs...
+    )
+
+    # Re-order the models AGAIN, since we might have swapped some.
+    @set! model.models = models_by_processes(ChainOrder(), chain2models, swapstate)
+
+    # Create the current state from `outerstate_prev` and `swapstate`, and `step` for `outersampler`.
+    outertransition, outerstate = AbstractMCMC.step(
+        # TODO: Do we really need this `state_from` here? `swapstate` shouldn't be changing the
+        # parameters + `outerstate_prev` and `swapstate` are both sorted according to processes,
+        # hence a `swap` doesn't matter here (and is accounted for by swapping the `models` above).
+        rng, model, outersampler, state_from(model, outerstate_prev, swapstate);


I haven't tested no, but it will work just fine.

But I'm thinking that I'll remove this for now + remove implementation of getparams_and_logprob for SwapState because I don't think it's quite clear what it should be doing. Basically, should getparams_and_logprob return

  1.  ordered according to internal representation (i.e. processes), or
  2.  ordered according to the models (which most othe samplers will expect)?

Before we concluded the above I think it's best to just error.

—
Reply to this email directly, view it on GitHub<https://github.com/TuringLang/MCMCTempering.jl/pull/152#discussion_r1132303494>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AIQUYBB7VC5SHEIFYCHT3TTW3MMJ5ANCNFSM6AAAAAAVRDHS5I>.
You are receiving this because you commented.Message ID: ***@***.***>

2023-03-10 14:41 UTC, torfjelde commented
Ah shit, I think I destroyed the commit history in an attempt to rebase here :confused: It looks like the diff is still okay though, so should be fine :+1:

2023-03-10 15:03 UTC, HarrisonWilde commented
Haha no worries, all looks great now, go ahead and merge!

2023-03-11 09:09 UTC, HarrisonWilde approved these changes

2023-03-11 10:37 UTC, torfjelde commented
If tests pass now, I'm merging.

In an attempt to make the tolerances used in the tests a bit more appropriate, I've gone with using the MCSE and basically doing hypothesis testing. The acutal significance levels don't mean much, but it provides an intuitive knob to tune wrt. how relaxed we want to be with the tests that adapts to the "problem" at hand. We should probably also use this approach more in the tests present in `runtests.jl`, but I'll leave this for now.

I've also just relaxed the ESS comparisons quite a bit globally as there seems to be a bit too much variance.

2023-03-11 11:42 UTC, merged